#!/usr/bin/env zsh
#
# ~/.zshrc
#

if [ -f ~/.aliases ]; then
    . ~/.aliases
fi

if [ -f ~/.path ]; then
    . ~/.path
fi

autoload -Uz compinit && compinit

# last/two %
export PROMPT='%F{green}%B%2~%b%f %# '

HISTSIZE=1000
SAVEHIST=1000
