#!/usr/bin/env python
import os
import sys
import zipfile

filename = sys.argv[1]
print("Extracting " + filename)
file = zipfile.ZipFile(filename, 'r')
for name in file.namelist():
    unbak_name = name.encode('cp437').decode('cp936')
    print("Extracting " + unbak_name)
    directory = os.path.dirname(unbak_name)
    if not os.path.exists(directory) and directory != '':
        os.makedirs(directory)

    data = file.read(name)
    if not os.path.exists(unbak_name):
        f = open(unbak_name, 'wb')
        f.write(data)
        f.close()
file.close()
