#!/bin/bash
# myinstall -- logs installed packages

installlog="$HOME/dotfiles/install.log"

if [ $# -eq 0 ]; then
    echo "Usage: $0 [-s] list of packages to install" >&2
    exit 1
fi

if [ "$(uname)" = "Darwin" ]; then
    if brew install "$@"; then
        if [ "$1" = "-s" ]; then
            shift               # Silent
        else
            echo "$(date "+%Y-%m-%d %H.%M.%S"): $*" >> "$installlog"
        fi
    else
        echo "Error: failed to install"
        exit 1
    fi
else
    echo "Error: unknown operating system"
    exit 1
fi

exit 0
