#!/usr/bin/env python
import json
import sys
import os
import argparse

def get_outline(j):
    if type(j) == list and len(j) > 5:
        return j[:5] + ['...']
    for key in j.keys():
        get_outline(j[key])
    return j

def main(filepath, outline=False):
    with open(filepath, 'r') as fin:
        j = json.load(fin)
        if outline:
            j = get_outline(j)
        obj = json.dumps(j, indent=4)
        print(obj)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Print formatted representation of json file')
    parser.add_argument('--outline', action='store_true')
    parser.add_argument('input')
    args = parser.parse_args()
    print(args.input, args.outline)
    main(args.input, outline=args.outline)
