#!/usr/bin/env python
import sys
import os

filenames = sys.argv[1:]

for filename in filenames:
    filename_output = os.path.join(os.path.dirname(filename),
                                   'utf8_' + os.path.basename(filename))

    fi = open(filename, 'r', encoding='gbk')
    if os.path.exists(filename_output):
        print("Error: File '"+ filename_output +"' already exists")
        continue
    fo = open(filename_output, 'w', encoding='utf8')

    fo.write(fi.read())

    fi.close()
    fo.close()
